name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      # Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # Build monorepo packages
      - name: Build Monorepo
        run: yarn build
