name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      TURBO_REMOTE_ONLY: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn

      - name: Build Monorepo
        run: yarn build

      - name: Set Git Identity
        run: |
          git config user.email "buttery-release-bot@butter.tools"
          git config user.name "Buttery Release Bot"

      - name: Release to npm & Github
        run: NPM_TOKEN=${{ secrets.NPM_TOKEN }} yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Create Release Pull Request or Publish to npm
      #   id: changesets
      #   uses: monoweave/github-action-preview@main
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     monoweave-command:
      #     preview-comment-title: "chore: Version & release packages"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
