name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions: write-all

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Dependencies
        run: yarn
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Build Monorepo
        run: yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set Git Identity
        run: |
          git config user.email "buttery-release-bot@butter.tools"
          git config user.name "Buttery Release Bot"

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: monoweave/github-action-preview@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          monoweave-command: yarn release
          preview-comment-title: "chore: Version & release packages"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
